### ISSUE TITLE
Top repository ranking is wrong order.

### ISSUE THREAD

**Issue by AtsushiSakai** [surbhioberoi/github-widget#22]
Hi. your widget is great!!
But I think the top repository ranking logic has a bug...

This is my HP with your widget.
http://atsushisakai.github.io/
You can see the top repository is cpp, and it's star number is 18.
However, I have a repository that have 27 stars..
https://github.com/AtsushiSakai/MATLABRobotics
I think the repo should be the top of the ranking.

Thanks.

**Comment by gaul** [comment]
@AtsushiSakai Does #21 resolve this issue?

**Comment by AtsushiSakai** [comment]
@andrewgaul 
Oh. Thanks you for your comment.
You are right. If the code in GitHub is used, it works correctly.
I think the code on CDN is not updated...
https://unpkg.com/github-card@1.2.1/dist/widget.js
Thank you for your help!!.

Atsushi
